import './burger-menu.js';
import './hero-slider.js';
import './tours-slider.js';
import './training-slider.js';
import './reviews-slider.js';
import './advantages-slider.js';
import './gallery-slider.js';
import './show-input-label.js';
import './validate-form.js';
